# Generated by Django 4.1.1 on 2022-09-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('message', models.JSONField(default={'state': 0})),
            ],
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('menu', models.IntegerField()),
                ('lang', models.IntegerField()),
            ],
        ),
    ]
